#
# Toolkit Backend Variables 
#
env = GDK_BACKEND=wayland,x11 # GTK: Use wayland if available, fall back to x11 if not.
env = SDL_VIDEODRIVER=wayland # Run SDL2 applications on Wayland. Remove or set to x11 if games that provide older versions of SDL cause compatibility issues
env = CLUTTER_BACKEND=wayland # Clutter package already has wayland enabled, this variable will force Clutter applications to try and use the Wayland backend
#
# XDG specific environment variables are often detected through portals and applications that may set those for you, however it is not a bad idea to set them explicitly.
#
env = XDG_CURRENT_DESKTOP=Hyprland
env = XDG_SESSION_TYPE=wayland
env = XDG_SESSION_DESKTOP=Hyprland
#
# QT variables
#
env = QT_AUTO_SCREEN_SCALE_FACTOR=1 # (From the QT documentation) enables automatic scaling, based on the monitor’s pixel density
env = QT_QPA_PLATFORM=wayland;xcb # Tell QT applications to use the Wayland backend, and fall back to x11 if Wayland is unavailable
env = QT_WAYLAND_DISABLE_WINDOWDECORATION=1 # Disables window decorations on QT applications
env = QT_QPA_PLATFORMTHEME=qt5ct # Tells QT based applications to pick your theme from qt5ct, use with Kvantum.
