#!/usr/bin/sh
HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000

export PATH="$HOME/.local/bin:$PATH"
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
# export PATH=$HOME/.local/share/go/bin:$PATH
# export GOPATH=$HOME/.local/share/go
# export PATH=$HOME/.miniconda/bin:$PATH
export npm_config_prefix=~/.node_modules
export PATH="$HOME/.node_modules/bin:$PATH"

eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
